# Generated by Django 4.1 on 2022-08-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('cast', models.CharField(max_length=5)),
                ('religion', models.CharField(max_length=10)),
                ('mother_toung', models.CharField(max_length=50)),
            ],
        ),
    ]
