# Generated by Django 4.1 on 2022-09-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pincode_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymaster',
            name='country_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='countrymaster',
            name='country_name',
            field=models.CharField(max_length=100),
        ),
    ]
